;; Everforest Theme
;; https://github.com/sainnhe/everforest

[base]
text               = d3c6aa
subtext            = 859289
nav-active-text    = dbc7f
main               = 2b3339
sidebar            = 2b3339
player             = 2b3339
card               = 2b3339
shadow             = 000000
main-secondary     = 2b3339
button             = 3d484d
button-secondary   = 83c092
button-active      = dbc7f
button-disabled    = 232a2e
nav-active         = 3d484d
play-button        = dbc7f
tab-active         = 2b3339
notification       = 2b3339
notification-error = 2b3339
playback-bar       = dbc7f
misc               = a7c080
