;; Catppuccin Mocha Theme

[base]
text               = cdd6f4
subtext            = 6c7086
nav-active-text    = f9e2af
main               = 1e1e2e
sidebar            = 1e1e2e
player             = 1e1e2e
card               = 1e1e2e
shadow             = 000000
main-secondary     = 1e1e2e
button             = 313244
button-secondary   = cba6f7
button-active      = f9e2af
button-disabled    = 181825
nav-active         = 313244
play-button        = f9e2af
tab-active         = 1e1e2e
notification       = 1e1e2e
notification-error = 1e1e2e
playback-bar       = f9e2af
misc               = bac2de
