# ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██╗      ██████╗  ██████╗██╗  ██╗
# ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██║     ██╔═══██╗██╔════╝██║ ██╔╝
# ███████║ ╚████╔╝ ██████╔╝██████╔╝██║     ██║   ██║██║     █████╔╝ 
# ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██║     ██║   ██║██║     ██╔═██╗ 
# ██║  ██║   ██║   ██║     ██║  ██║███████╗╚██████╔╝╚██████╗██║  ██╗
# ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚══════╝ ╚═════╝  ╚═════╝╚═╝  ╚═╝
                                                                  
# source = colors.conf

$color = rgba(000000ff)
$inner_color = rgba(000000a8)
$outer_color = rgba(747474ff)
$font_color = rgba(ffffffff)
$placeholder_color = rgba(ffffffb3)
$check_color = rgba(868686ff)

background {
    monitor =
    path = $HOME/.config/hyprluggage/current/wallpaper   # only png supported for now
    color = $color
    blur_passes = 2 # 0 disables blurring
}
image {
    monitor =
    path = ~/hyprluggage/assets/luggage_open.png
    border_color = 0xffdddddd
    border_size = 0
    size = 250
    position = -5, 90
    halign = center
    valign = center
}
animations {
    enabled = true  
}

input-field {
    monitor =
    size = 450, 50
    position = 0, -100
    halign = center
    valign = center

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 4

    font_family = CaskaydiaMono Nerd Font
    font_color = $font_color

    placeholder_text = Enter Password 󰈷 
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 6
    shadow_passes = 0
    fade_on_empty = false
}
label {
    monitor = 
    text = $USER
    color = rgba(f2f3f4bf)
    font_size = 24
    font_family = SF Pro Display Bold
    position = -5, -500
    halign = center
    valign = center
}
auth {
    fingerprint:enabled = true
}

