-- AUTO-GENERATED by hypr-vnc-mod-gen.sh — do not edit
-- 116 unique VNC binds | failed: 0

local home = os.getenv("HOME")
local terminal = "kitty"
local browser = home .. "/.config/hypr/scripts/launch-browser"
local browser2 = "zen-browser"
local webapp = home .. "/.config/hypr/scripts/launch-webapp"
local focus = home .. "/.config/hypr/scripts/focus"
local osdclient = "swayosd-client --monitor \"$(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name')\""
local rofiDir = home .. "/.config/rofi/scripts"
local scrDir = home .. "/.config/hypr/scripts"

-- from: bindd = Super ALT, M, easyeffects, exec, easyeffects
-- VNC: SUPER ALT + M → CTRL ALT SHIFT + E
hl.bind("CTRL + ALT + SHIFT + E", hl.dsp.exec_cmd("easyeffects"), { description = "EasyEffects (VNC)" })

-- from: bindd = SUPER CTRL, F12, Restart Sunshine, exec, pkill sunshine && sunshine &
-- VNC: SUPER CTRL + F12 → CTRL ALT SHIFT + F12
hl.bind("CTRL + ALT + SHIFT + F12", hl.dsp.exec_cmd("pkill sunshine && sunshine &"), { description = "Restart Sunshine (VNC)" })

-- from: bindd = SUPER CTRL, A, Gemini, exec, $webapp "https://gemini.google.com"
-- VNC: SUPER CTRL + A → CTRL ALT SHIFT + F6
hl.bind("CTRL + ALT + SHIFT + F6", hl.dsp.exec_cmd(string.format("%s \"https://gemini.google.com\"", webapp)), { description = "Gemini (VNC)" })

-- from: bindd = SUPER SHIFT, RETURN, Attach tmux session, exec, $terminal -e tmux a
-- VNC: SUPER SHIFT + RETURN → CTRL ALT SHIFT + RETURN
hl.bind("CTRL + ALT + SHIFT + RETURN", hl.dsp.exec_cmd(string.format("%s -e tmux a", terminal)), { description = "Attach tmux (VNC)" })

-- from: bindd = SUPER ALT, RETURN, New tmux session, exec, $terminal -e tmux new -As main
-- VNC: SUPER ALT + RETURN → CTRL ALT SHIFT + apostrophe
hl.bind("CTRL + ALT + SHIFT + apostrophe", hl.dsp.exec_cmd(string.format("%s -e tmux new -As main", terminal)), { description = "New tmux session (VNC)" })

-- from: bindd = SUPER SHIFT,I,Web App Install, exec, kitty --title webapp-install -e $scrDir/webapp-install
-- VNC: SUPER SHIFT + I → CTRL ALT SHIFT + I
hl.bind("CTRL + ALT + SHIFT + I", hl.dsp.exec_cmd(string.format("kitty --title webapp-install -e %s/webapp-install", scrDir)), { description = "Web App Install (VNC)" })

-- from: bindd = SUPER , SPACE, app-launcher, exec, pkill rofi || rofi -show drun
-- VNC: SUPER + SPACE → CTRL ALT + SPACE
hl.bind("CTRL + ALT + SPACE", hl.dsp.exec_cmd("pkill rofi || rofi -show drun"), { description = "app-launcher" })

-- from: bindd = SUPER CTRL, B, Power Profiles, exec,   $rofiDir/power-profiles
-- VNC: SUPER CTRL + B → CTRL ALT SHIFT + B
hl.bind("CTRL + ALT + SHIFT + B", hl.dsp.exec_cmd(string.format("%s/power-profiles", rofiDir)), { description = "Power Profiles (VNC)" })

-- from: bindd = SUPER SHIFT, SPACE, Toggle waybar, exec, $scrDir/toggle-waybar
-- VNC: SUPER SHIFT + SPACE → CTRL ALT SHIFT + W
hl.bind("CTRL + ALT + SHIFT + W", hl.dsp.exec_cmd(string.format("%s/toggle-waybar", scrDir)), { description = "Toggle waybar (Super+Shift+Space)" })

-- from: bindd = SUPER CTRL, N, Nightlight, exec, $scrDir/nightlight
-- VNC: SUPER CTRL + N → CTRL ALT SHIFT + F5
hl.bind("CTRL + ALT + SHIFT + F5", hl.dsp.exec_cmd(string.format("%s/nightlight", scrDir)), { description = "Nightlight (VNC)" })

-- from: bindd = SUPER CTRL, I, Toggle Idle/Lock, exec, $scrDir/toggle-idle
-- VNC: SUPER CTRL + I → CTRL ALT SHIFT + O
hl.bind("CTRL + ALT + SHIFT + O", hl.dsp.exec_cmd(string.format("%s/toggle-idle", scrDir)), { description = "Toggle Idle/Lock (VNC)" })

-- from: bindd = SUPER ALT, S, Share file, exec, kitty --title share -e $scrDir/fileshare file
-- VNC: SUPER ALT + S → CTRL ALT SHIFT + F
hl.bind("CTRL + ALT + SHIFT + F", hl.dsp.exec_cmd(string.format("kitty --title share -e %s/fileshare file", scrDir)), { description = "Share file (VNC)" })

-- from: bindd = SUPER CTRL, S, Share folder, exec, kitty --title share -e $scrDir/fileshare folder
-- VNC: SUPER CTRL + S → CTRL ALT SHIFT + D
hl.bind("CTRL + ALT + SHIFT + D", hl.dsp.exec_cmd(string.format("kitty --title share -e %s/fileshare folder", scrDir)), { description = "Share folder (VNC)" })

-- from: bindd = SUPER SHIFT, S, Share clipboard, exec, kitty --title share -e $scrDir/fileshare clipboard
-- VNC: SUPER SHIFT + S → CTRL ALT SHIFT + S
hl.bind("CTRL + ALT + SHIFT + S", hl.dsp.exec_cmd(string.format("kitty --title share -e %s/fileshare clipboard", scrDir)), { description = "Share clipboard (VNC)" })

-- from: bindd = SUPER CTRL, SPACE, Theme Matugen apply, exec, $rofiDir/selectWall
-- VNC: SUPER CTRL + SPACE → CTRL ALT SHIFT + T
hl.bind("CTRL + ALT + SHIFT + T", hl.dsp.exec_cmd(string.format("%s/selectWall", rofiDir)), { description = "Theme Matugen apply (Super+Ctrl+Space)" })

-- from: bindd = SUPER ALT, SPACE, Theme wallpaper picker, exec, $rofiDir/wallPicker
-- VNC: SUPER ALT + SPACE → CTRL ALT SHIFT + SPACE
hl.bind("CTRL + ALT + SHIFT + SPACE", hl.dsp.exec_cmd(string.format("%s/wallPicker", rofiDir)), { description = "Theme wallpaper picker (Super+Alt+Space)" })

-- from: bindd = SUPER CTRL ALT, SPACE, Theme random wallpaper, exec, $scrDir/change-theme
-- VNC: SUPER CTRL ALT + SPACE → CTRL ALT SHIFT + G
hl.bind("CTRL + ALT + SHIFT + G", hl.dsp.exec_cmd(string.format("%s/change-theme", scrDir)), { description = "Theme random wallpaper (Super+Ctrl+Alt+Space)" })

-- from: bindd = SUPER CTRL SHIFT , SPACE, Theme switcher, exec, ~/hyprluggage/install/themes/hyprluggage switch
-- VNC: SUPER CTRL SHIFT + SPACE → CTRL ALT SHIFT + Y
hl.bind("CTRL + ALT + SHIFT + Y", hl.dsp.exec_cmd(string.format("%s/hyprluggage/install/themes/hyprluggage switch", home)), { description = "Theme switcher (Super+Ctrl+Shift+Space)" })

-- from: bindd = SUPER, I, Theme Hyprluggage TUI, exec, kitty --title hyprluggage-tui -e ~/hyprluggage/install/themes/hyprluggage-tui
-- VNC: SUPER + I → CTRL ALT + I
hl.bind("CTRL + ALT + I", hl.dsp.exec_cmd(string.format("kitty --title hyprluggage-tui -e %s/hyprluggage/install/themes/hyprluggage-tui", home)), { description = "Theme Hyprluggage TUI" })

-- from: bindd = SUPER ALT, I, Theme browse, exec, kitty --title hyprluggage-browse -e ~/hyprluggage/install/themes/hyprluggage browse
-- VNC: SUPER ALT + I → CTRL ALT SHIFT + U
hl.bind("CTRL + ALT + SHIFT + U", hl.dsp.exec_cmd(string.format("kitty --title hyprluggage-browse -e %s/hyprluggage/install/themes/hyprluggage browse", home)), { description = "Theme browse (Super+Alt+I)" })

-- from: bindd = SUPER ALT, up, Theme wallpapers cycle, exec, $scrDir/cycle-wallpaper
-- VNC: SUPER ALT + up → CTRL ALT SHIFT + up
hl.bind("CTRL + ALT + SHIFT + up", hl.dsp.exec_cmd(string.format("%s/cycle-wallpaper", scrDir)), { description = "Theme wallpapers cycle (Super+Alt+Up)" })

-- from: bindd = SUPER ALT, right, Theme next wallpaper, exec, $scrDir/cycle-wallpaper next
-- VNC: SUPER ALT + right → CTRL ALT SHIFT + right
hl.bind("CTRL + ALT + SHIFT + right", hl.dsp.exec_cmd(string.format("%s/cycle-wallpaper next", scrDir)), { description = "Theme next wallpaper (Super+Alt+Right)" })

-- from: bindd = SUPER ALT, left, Theme previous wallpaper, exec, $scrDir/cycle-wallpaper prev
-- VNC: SUPER ALT + left → CTRL ALT SHIFT + left
hl.bind("CTRL + ALT + SHIFT + left", hl.dsp.exec_cmd(string.format("%s/cycle-wallpaper prev", scrDir)), { description = "Theme previous wallpaper (Super+Alt+Left)" })

-- from: bindd = SUPER SHIFT, L, lock screen, exec, $scrDir/lock-screen
-- VNC: SUPER SHIFT + L → CTRL ALT SHIFT + F3
hl.bind("CTRL + ALT + SHIFT + F3", hl.dsp.exec_cmd(string.format("%s/lock-screen", scrDir)), { description = "Lock screen (VNC)" })

-- from: bindd = SUPER CTRL, up, reboot, exec, $scrDir/graceful-reboot
-- VNC: SUPER CTRL + up → CTRL ALT SHIFT + Escape
hl.bind("CTRL + ALT + SHIFT + Escape", hl.dsp.exec_cmd(string.format("%s/graceful-reboot", scrDir)), { description = "Reboot (VNC)" })

-- from: bindd = SUPER CTRL, BACKSPACE , Toggle focus & vibe mode, exec, $scrDir/toggle-focus
-- VNC: SUPER CTRL + BACKSPACE → CTRL ALT SHIFT + BACKSPACE
hl.bind("CTRL + ALT + SHIFT + BACKSPACE", hl.dsp.exec_cmd(string.format("%s/toggle-focus", scrDir)), { description = "Toggle focus/vibe (VNC)" })

-- from: bindd = SUPER , R, Screen recording, exec, $scrDir/screenrecord --with-desktop-audio
-- VNC: SUPER + R → CTRL ALT + R
hl.bind("CTRL + ALT + R", hl.dsp.exec_cmd(string.format("%s/screenrecord --with-desktop-audio", scrDir)), { description = "Screen recording" })

-- from: bindd = SUPER SHIFT, R, Screen recording + mic, exec, $scrDir/screenrecord --with-microphone-audio
-- VNC: SUPER SHIFT + R → CTRL ALT SHIFT + R
hl.bind("CTRL + ALT + SHIFT + R", hl.dsp.exec_cmd(string.format("%s/screenrecord --with-microphone-audio", scrDir)), { description = "Screen recording + mic (VNC)" })

-- from: bindd = SUPER ALT, R, Screen recording + mic + webcam, exec, $scrDir/screenrecord --with-desktop-audio --with-microphone-audio --with-webcam
-- VNC: SUPER ALT + R → CTRL ALT SHIFT + V
hl.bind("CTRL + ALT + SHIFT + V", hl.dsp.exec_cmd(string.format("%s/screenrecord --with-desktop-audio --with-microphone-audio --with-webcam", scrDir)), { description = "Screen recording + mic + webcam (VNC)" })

-- from: bindd = SUPER ALT, XF86AudioRaiseVolume, Brightness up, exec, $osdclient --brightness raise
-- VNC: SUPER ALT + XF86AudioRaiseVolume → CTRL ALT SHIFT + XF86AudioRaiseVolume
hl.bind("CTRL + ALT + SHIFT + XF86AudioRaiseVolume", hl.dsp.exec_cmd(string.format("%s --brightness raise", osdclient)), { description = "Brightness up" })

-- from: bindd = SUPER ALT, XF86AudioLowerVolume, Brightness down, exec, $osdclient --brightness lower
-- VNC: SUPER ALT + XF86AudioLowerVolume → CTRL ALT SHIFT + XF86AudioLowerVolume
hl.bind("CTRL + ALT + SHIFT + XF86AudioLowerVolume", hl.dsp.exec_cmd(string.format("%s --brightness lower", osdclient)), { description = "Brightness down" })

-- from: bindd = SUPER SHIFT, LEFT, Swap window to the left, swapwindow, l
-- VNC: SUPER SHIFT + LEFT → CTRL ALT SHIFT + H
hl.bind("CTRL + ALT + SHIFT + H", hl.dsp.window.swap({ direction = "left" }), { description = "Swap window left (VNC)" })

-- from: bindd = SUPER SHIFT, RIGHT, Swap window to the right, swapwindow, r
-- VNC: SUPER SHIFT + RIGHT → CTRL ALT SHIFT + L
hl.bind("CTRL + ALT + SHIFT + L", hl.dsp.window.swap({ direction = "right" }), { description = "Swap window right (VNC)" })

-- from: bindd = SUPER SHIFT, UP, Swap window up, swapwindow, u
-- VNC: SUPER SHIFT + UP → CTRL ALT SHIFT + K
hl.bind("CTRL + ALT + SHIFT + K", hl.dsp.window.swap({ direction = "up" }), { description = "Swap window up (VNC)" })

-- from: bindd = SUPER SHIFT, DOWN, Swap window down, swapwindow, d
-- VNC: SUPER SHIFT + DOWN → CTRL ALT SHIFT + J
hl.bind("CTRL + ALT + SHIFT + J", hl.dsp.window.swap({ direction = "down" }), { description = "Swap window down (VNC)" })

-- from: bindd = SUPER CTRL, LEFT, Previous workspace, workspace, e-1
-- VNC: SUPER CTRL + LEFT → CTRL ALT SHIFT + comma
hl.bind("CTRL + ALT + SHIFT + comma", hl.dsp.focus({ workspace = "e-1" }), { description = "Previous workspace (VNC)" })

-- from: bindd = SUPER CTRL, RIGHT, Next workspace, workspace, e+1
-- VNC: SUPER CTRL + RIGHT → CTRL ALT SHIFT + period
hl.bind("CTRL + ALT + SHIFT + period", hl.dsp.focus({ workspace = "e+1" }), { description = "Next workspace (VNC)" })

-- from: bindd = SUPER ALT, H, Laptop screen off, exec, hyprctl keyword monitor "eDP-1,disable"
-- VNC: SUPER ALT + H → CTRL ALT SHIFT + F1
hl.bind("CTRL + ALT + SHIFT + F1", hl.dsp.exec_cmd("hyprctl keyword monitor \"eDP-1,disable\""), { description = "Laptop screen off (VNC)" })

-- from: bindd = SUPER ALT, l, Laptop screen on , exec, hyprctl keyword monitor "eDP-1, preferred, 0x0, 1"
-- VNC: SUPER ALT + l → CTRL ALT SHIFT + F2
hl.bind("CTRL + ALT + SHIFT + F2", hl.dsp.exec_cmd("hyprctl keyword monitor \"eDP-1,preferred,0x0,1\""), { description = "Laptop screen on (VNC)" })

-- from: bindd = SUPER ,ESCAPE , powermenu , exec, $rofiDir/powermenu
hl.bind("CTRL + ALT + ESCAPE", hl.dsp.exec_cmd(string.format("%s/powermenu", rofiDir)), { description = "powermenu" })

-- from: bindd = SUPER, A, Perplexity, exec, $webapp "https://perplexity.ai"
hl.bind("CTRL + ALT + A", hl.dsp.exec_cmd(string.format("%s \"https://perplexity.ai\"", webapp)), { description = "Perplexity" })

-- from: bindd = SUPER, B, Browser, exec,  $browser
hl.bind("CTRL + ALT + B", hl.dsp.exec_cmd(string.format("%s", browser)), { description = "Browser" })

-- from: bindd = SUPER, BACKSLASH, Learn, exec, $webapp "https://devhints.io/"
hl.bind("CTRL + ALT + BACKSLASH", hl.dsp.exec_cmd(string.format("%s \"https://devhints.io/\"", webapp)), { description = "Learn" })

-- from: bindd = SUPER, BACKSPACE , Terminal Transparency , exec, $scrDir/toggle-terminal-transparency
hl.bind("CTRL + ALT + BACKSPACE", hl.dsp.exec_cmd(string.format("%s/toggle-terminal-transparency", scrDir)), { description = "Terminal Transparency" })

-- from: bindd = SUPER, C, Cursor, exec, uwsm app -- cursor.desktop
hl.bind("CTRL + ALT + C", hl.dsp.exec_cmd("uwsm app -- cursor.desktop"), { description = "Cursor" })

-- from: bindd = SUPER, D, Discord, exec, uwsm app -- discord
hl.bind("CTRL + ALT + D", hl.dsp.exec_cmd("uwsm app -- discord"), { description = "Discord" })

-- from: bindd = SUPER, E, File manager, exec, uwsm app -- thunar
hl.bind("CTRL + ALT + E", hl.dsp.exec_cmd("uwsm app -- thunar"), { description = "File manager" })

-- from: bindd = SUPER, F1,Toggle Monitor Power, exec, $scrDir/toggle-monitor
hl.bind("CTRL + ALT + F1", hl.dsp.exec_cmd(string.format("%s/toggle-monitor", scrDir)), { description = "Toggle Monitor Power" })

-- from: bindd = SUPER, G, Github, exec, $webapp "https://github.com/Jmartgraphix"
hl.bind("CTRL + ALT + G", hl.dsp.exec_cmd(string.format("%s \"https://github.com/Jmartgraphix\"", webapp)), { description = "Github" })

-- from: bindd = SUPER, K, Show all keybindings, exec, $rofiDir/keyhints
hl.bind("CTRL + ALT + K", hl.dsp.exec_cmd(string.format("%s/keyhints", rofiDir)), { description = "Show all keybindings" })

-- from: bindd = SUPER, L, Screensaver, exec, $scrDir/screensaver-launch
hl.bind("CTRL + ALT + L", hl.dsp.exec_cmd(string.format("%s/screensaver-launch", scrDir)), { description = "Screensaver" })

-- from: bindd = SUPER, M, Music, exec, $focus spotify spotify-launcher
hl.bind("CTRL + ALT + M", hl.dsp.exec_cmd(string.format("%s spotify spotify-launcher", focus)), { description = "Music" })

-- from: bindd = SUPER, N, Dismiss Notifications, exec, makoctl dismiss -a
hl.bind("CTRL + ALT + N", hl.dsp.exec_cmd("makoctl dismiss -a"), { description = "Dismiss Notifications" })

-- from: bindd = SUPER, O, obsidian, exec, obsidian # --disable-gpu
hl.bind("CTRL + ALT + O", hl.dsp.exec_cmd("obsidian # --disable-gpu"), { description = "obsidian" })

-- from: bindd = SUPER, P, Screenshot with editing, exec, $scrDir/screenshot
hl.bind("CTRL + ALT + P", hl.dsp.exec_cmd(string.format("%s/screenshot", scrDir)), { description = "Screenshot with editing" })

-- from: bindd = SUPER, Q, Close window, killactive,
hl.bind("CTRL + ALT + Q", hl.dsp.window.close(), { description = "Close window" })

-- from: bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- $terminal --dir="$(cwd-terminal)"
hl.bind("CTRL + ALT + RETURN", hl.dsp.exec_cmd(string.format("uwsm-app -- %s --dir=\"$(cwd-terminal)\"", terminal)), { description = "Terminal" })

-- from: bindd = SUPER, S, Wiremix, exec, $terminal --class=Wiremix -e wiremix
hl.bind("CTRL + ALT + S", hl.dsp.exec_cmd(string.format("%s --class=Wiremix -e wiremix", terminal)), { description = "Wiremix" })

-- from: bindd = SUPER, T, Todoist, exec, $webapp "https://app.todoist.com"
hl.bind("CTRL + ALT + T", hl.dsp.exec_cmd(string.format("%s \"https://app.todoist.com\"", webapp)), { description = "Todoist" })

-- from: bindd = SUPER, W, WhatsApp, exec, $webapp "https://web.whatsapp.com/"
hl.bind("CTRL + ALT + W", hl.dsp.exec_cmd(string.format("%s \"https://web.whatsapp.com/\"", webapp)), { description = "WhatsApp" })

-- from: bindd = SUPER, X, X, exec, $webapp "https://x.com/"
hl.bind("CTRL + ALT + X", hl.dsp.exec_cmd(string.format("%s \"https://x.com/\"", webapp)), { description = "X" })

-- from: bindd = SUPER, XF86AudioLowerVolume, Monitor Brightness down, exec, ddcutil setvcp 10 - 10
hl.bind("CTRL + ALT + XF86AudioLowerVolume", hl.dsp.exec_cmd("ddcutil setvcp 10 - 10"), { description = "Monitor Brightness down" })

-- from: bindd = SUPER, XF86AudioRaiseVolume, Monitor Brightness up, exec, ddcutil setvcp 10 + 10
hl.bind("CTRL + ALT + XF86AudioRaiseVolume", hl.dsp.exec_cmd("ddcutil setvcp 10 + 10"), { description = "Monitor Brightness up" })

-- from: bindd = SUPER, Y, YouTube, exec, $webapp "https://youtube.com/"
hl.bind("CTRL + ALT + Y", hl.dsp.exec_cmd(string.format("%s \"https://youtube.com/\"", webapp)), { description = "YouTube" })

-- from: bindd = SUPER, Z, Linkedin, exec, $webapp "https://www.linkedin.com/feed/"
hl.bind("CTRL + ALT + Z", hl.dsp.exec_cmd(string.format("%s \"https://www.linkedin.com/feed/\"", webapp)), { description = "Linkedin" })

-- from: bindd = SUPER, slash, Passwords, exec, uwsm app -- bitwarden-desktop
hl.bind("CTRL + ALT + slash", hl.dsp.exec_cmd("uwsm app -- bitwarden-desktop"), { description = "Passwords" })

-- from: bindd = SUPER, F10, mpc prev, exec , mpc prev
hl.bind("CTRL + ALT + F10", hl.dsp.exec_cmd("mpc prev"), { description = "mpc prev" })

-- from: bindd = SUPER, F11, mpc play, exec , mpc play
hl.bind("CTRL + ALT + F11", hl.dsp.exec_cmd("mpc play"), { description = "mpc play" })

-- from: bindd = SUPER, F12, MPC next track, exec, mpc next
hl.bind("CTRL + ALT + F12", hl.dsp.exec_cmd("mpc next"), { description = "MPC next track" })

-- from: bindd = SUPER, F9, mpc pause, exec , mpc pause
hl.bind("CTRL + ALT + F9", hl.dsp.exec_cmd("mpc pause"), { description = "mpc pause" })

-- from: bindld = SUPER, XF86AudioMute, Switch audio output, exec, $scrDir/audio-switch
hl.bind("CTRL + ALT + XF86AudioMute", hl.dsp.exec_cmd(string.format("%s/audio-switch", scrDir)), { description = "Switch audio output", locked = true })

-- from: bindd = SUPER , V, Pseudo window, pseudo, # dwindle
hl.bind("CTRL + ALT + V", hl.dsp.window.pseudo(), { description = "Pseudo window" })

-- from: bindd = SUPER, DOWN, Move window focus down, movefocus, d
hl.bind("CTRL + ALT + DOWN", hl.dsp.focus({ direction = "down" }), { description = "Move window focus down" })

-- from: bindd = SUPER, F, Fullscreen, fullscreen
hl.bind("CTRL + ALT + F", hl.dsp.window.fullscreen(), { description = "Fullscreen" })

-- from: bindd = SUPER, H, Move window focus left, movefocus, l
hl.bind("CTRL + ALT + H", hl.dsp.focus({ direction = "left" }), { description = "Move window focus left" })

-- from: bindd = SUPER, J, Move window focus down, movefocus, d
hl.bind("CTRL + ALT + J", hl.dsp.focus({ direction = "down" }), { description = "Move window focus down" })

-- from: bindd = SUPER, LEFT, Move window focus left, movefocus, l
hl.bind("CTRL + ALT + LEFT", hl.dsp.focus({ direction = "left" }), { description = "Move window focus left" })

-- from: bindd = SUPER, RIGHT, Move window focus right, movefocus, r
hl.bind("CTRL + ALT + RIGHT", hl.dsp.focus({ direction = "right" }), { description = "Move window focus right" })

-- from: bindd = SUPER, TAB, Previous workspace, workspace, previous
hl.bind("CTRL + ALT + TAB", hl.dsp.focus({ workspace = "previous" }), { description = "Previous workspace" })

-- from: bindd = SUPER, UP, Move window focus up, movefocus, u
hl.bind("CTRL + ALT + UP", hl.dsp.focus({ direction = "up" }), { description = "Move window focus up" })

-- from: bindd = SUPER, code:10, Switch to workspace 1, workspace, 1
hl.bind("CTRL + ALT + code:10", hl.dsp.focus({ workspace = 1 }), { description = "Switch to workspace 1" })

-- from: bindd = SUPER, code:11, Switch to workspace 2, workspace, 2
hl.bind("CTRL + ALT + code:11", hl.dsp.focus({ workspace = 2 }), { description = "Switch to workspace 2" })

-- from: bindd = SUPER, code:12, Switch to workspace 3, workspace, 3
hl.bind("CTRL + ALT + code:12", hl.dsp.focus({ workspace = 3 }), { description = "Switch to workspace 3" })

-- from: bindd = SUPER, code:13, Switch to workspace 4, workspace, 4
hl.bind("CTRL + ALT + code:13", hl.dsp.focus({ workspace = 4 }), { description = "Switch to workspace 4" })

-- from: bindd = SUPER, code:14, Switch to workspace 5, workspace, 5
hl.bind("CTRL + ALT + code:14", hl.dsp.focus({ workspace = 5 }), { description = "Switch to workspace 5" })

-- from: bindd = SUPER, code:15, Switch to workspace 6, workspace, 6
hl.bind("CTRL + ALT + code:15", hl.dsp.focus({ workspace = 6 }), { description = "Switch to workspace 6" })

-- from: bindd = SUPER, code:16, Switch to workspace 7, workspace, 7
hl.bind("CTRL + ALT + code:16", hl.dsp.focus({ workspace = 7 }), { description = "Switch to workspace 7" })

-- from: bindd = SUPER, code:17, Switch to workspace 8, workspace, 8
hl.bind("CTRL + ALT + code:17", hl.dsp.focus({ workspace = 8 }), { description = "Switch to workspace 8" })

-- from: bindd = SUPER, code:18, Switch to workspace 9, workspace, 9
hl.bind("CTRL + ALT + code:18", hl.dsp.focus({ workspace = 9 }), { description = "Switch to workspace 9" })

-- from: bindd = SUPER, code:19, Switch to workspace 10, workspace, 10
hl.bind("CTRL + ALT + code:19", hl.dsp.focus({ workspace = 10 }), { description = "Switch to workspace 10" })

-- from: bindd = SUPER, code:20, Expand window left, resizeactive, -100 0    # - key
hl.bind("CTRL + ALT + code:20", hl.dsp.window.resize({ x = -100, y = 0, relative = true }), { description = "Expand window left" })

-- from: bindd = SUPER, code:21, Shrink window left, resizeactive, 100 0     # = key
hl.bind("CTRL + ALT + code:21", hl.dsp.window.resize({ x = 100, y = 0, relative = true }), { description = "Shrink window left" })

-- from: bindd = SUPER, mouse_down, Scroll active workspace forward, workspace, e+1
hl.bind("CTRL + ALT + mouse_down", hl.dsp.focus({ workspace = "e+1" }), { description = "Scroll active workspace forward" })

-- from: bindd = SUPER, mouse_up, Scroll active workspace backward, workspace, e-1
hl.bind("CTRL + ALT + mouse_up", hl.dsp.focus({ workspace = "e-1" }), { description = "Scroll active workspace backward" })

-- from: bindmd = SUPER, mouse:272, Move window, movewindow
hl.bind("CTRL + ALT + mouse:272", hl.dsp.window.drag(), { description = "Move window", mouse = true })

-- from: bindmd = SUPER, mouse:273, Resize window, resizewindow
hl.bind("CTRL + ALT + mouse:273", hl.dsp.window.resize(), { description = "Resize window", mouse = true })

-- from: bindd = SUPER SHIFT, A, ChatGPT, exec, $webapp "https://chatgpt.com"
hl.bind("CTRL + ALT + SHIFT + A", hl.dsp.exec_cmd(string.format("%s \"https://chatgpt.com\"", webapp)), { description = "ChatGPT" })

-- from: bindd = SUPER SHIFT, C, Cava visualizer, exec, ~/.config/hypr/scripts/cava-launcher toggle
hl.bind("CTRL + ALT + SHIFT + C", hl.dsp.exec_cmd(string.format("%s/.config/hypr/scripts/cava-launcher toggle", home)), { description = "Cava visualizer" })

-- from: bindd = SUPER SHIFT, D, Docker, exec, $terminal -e lazydocker
-- VNC: SUPER SHIFT + D → CTRL ALT SHIFT + Q
hl.bind("CTRL + ALT + SHIFT + Q", hl.dsp.exec_cmd(string.format("%s -e lazydocker", terminal)), { description = "Docker" })

-- from: bindd = SUPER SHIFT, G, Gmail, exec, $webapp "https://mail.google.com/mail/u/1/"
-- VNC: SUPER SHIFT + G → CTRL ALT SHIFT + Z
hl.bind("CTRL + ALT + SHIFT + Z", hl.dsp.exec_cmd(string.format("%s \"https://mail.google.com/mail/u/1/\"", webapp)), { description = "Gmail" })

-- from: bindd = SUPER SHIFT, K,kill application, exec, hyprctl kill
-- VNC: SUPER SHIFT + K → CTRL ALT SHIFT + X
hl.bind("CTRL + ALT + SHIFT + X", hl.dsp.exec_cmd("hyprctl kill"), { description = "kill application" })

-- from: bindd = SUPER SHIFT, M, rofibeats, exec, $rofiDir/rofibeats
hl.bind("CTRL + ALT + SHIFT + M", hl.dsp.exec_cmd(string.format("%s/rofibeats", rofiDir)), { description = "rofibeats" })

-- from: bindd = SUPER SHIFT, N, Wifi Menu ,exec, $rofiDir/wifi
hl.bind("CTRL + ALT + SHIFT + N", hl.dsp.exec_cmd(string.format("%s/wifi", rofiDir)), { description = "Wifi Menu" })

-- from: bindd = SUPER SHIFT, O, Pop window out (float & pin), exec, $scrDir/pop-window
-- VNC: SUPER SHIFT + O → CTRL ALT SHIFT + P
hl.bind("CTRL + ALT + SHIFT + P", hl.dsp.exec_cmd(string.format("%s/pop-window", scrDir)), { description = "Pop window out (float & pin)" })

-- from: bindd =SUPER SHIFT , P, Color picker, exec, pkill hyprpicker || hyprpicker -a
-- VNC: SUPER SHIFT + P → CTRL ALT SHIFT + 1
hl.bind("CTRL + ALT + SHIFT + 1", hl.dsp.exec_cmd("pkill hyprpicker || hyprpicker -a"), { description = "Color picker" })

-- from: bindd = SUPER SHIFT, V, Toggle floating, togglefloating,
-- VNC: SUPER SHIFT + V → CTRL ALT SHIFT + 2
hl.bind("CTRL + ALT + SHIFT + 2", hl.dsp.window.float(), { description = "Toggle floating" })

-- from: bindd = SUPER SHIFT, code:10, Move window to workspace 1, movetoworkspace, 1
hl.bind("CTRL + ALT + SHIFT + code:10", hl.dsp.window.move({ workspace = 1 }), { description = "Move window to workspace 1" })

-- from: bindd = SUPER SHIFT, code:11, Move window to workspace 2, movetoworkspace, 2
hl.bind("CTRL + ALT + SHIFT + code:11", hl.dsp.window.move({ workspace = 2 }), { description = "Move window to workspace 2" })

-- from: bindd = SUPER SHIFT, code:12, Move window to workspace 3, movetoworkspace, 3
hl.bind("CTRL + ALT + SHIFT + code:12", hl.dsp.window.move({ workspace = 3 }), { description = "Move window to workspace 3" })

-- from: bindd = SUPER SHIFT, code:13, Move window to workspace 4, movetoworkspace, 4
hl.bind("CTRL + ALT + SHIFT + code:13", hl.dsp.window.move({ workspace = 4 }), { description = "Move window to workspace 4" })

-- from: bindd = SUPER SHIFT, code:14, Move window to workspace 5, movetoworkspace, 5
hl.bind("CTRL + ALT + SHIFT + code:14", hl.dsp.window.move({ workspace = 5 }), { description = "Move window to workspace 5" })

-- from: bindd = SUPER SHIFT, code:15, Move window to workspace 6, movetoworkspace, 6
hl.bind("CTRL + ALT + SHIFT + code:15", hl.dsp.window.move({ workspace = 6 }), { description = "Move window to workspace 6" })

-- from: bindd = SUPER SHIFT, code:16, Move window to workspace 7, movetoworkspace, 7
hl.bind("CTRL + ALT + SHIFT + code:16", hl.dsp.window.move({ workspace = 7 }), { description = "Move window to workspace 7" })

-- from: bindd = SUPER SHIFT, code:17, Move window to workspace 8, movetoworkspace, 8
hl.bind("CTRL + ALT + SHIFT + code:17", hl.dsp.window.move({ workspace = 8 }), { description = "Move window to workspace 8" })

-- from: bindd = SUPER SHIFT, code:18, Move window to workspace 9, movetoworkspace, 9
hl.bind("CTRL + ALT + SHIFT + code:18", hl.dsp.window.move({ workspace = 9 }), { description = "Move window to workspace 9" })

-- from: bindd = SUPER SHIFT, code:19, Move window to workspace 10, movetoworkspace, 10
hl.bind("CTRL + ALT + SHIFT + code:19", hl.dsp.window.move({ workspace = 10 }), { description = "Move window to workspace 10" })

