## Octarine Theme
## The color of magic from Discworld

general {
col.active_border = rgba(A8FF54aa)
}

# Border colors
$secondary = rgba(D17FF7aa)
$outline_variant = rgba(3A355066)

# Shadow configuration
decoration {
    shadow {
        color = rgba(168, 255, 84, 0.25)
        color_inactive = rgba(168, 255, 84, 0.15)
        offset = 2 2
        range = 8
        render_power = 3
    }
}
