;; Hyprluggage
;; Author: Jmartgraphix
;; Theme: Octarine - The color of magic from Discworld

[base]
text               = e8f0e0
subtext            = 7a7a6a
nav-active-text    = a8ff54
main               = 0a0710
sidebar            = 0a0710
player             = 0a0710
card               = 0a0710
shadow             = 000000
main-secondary     = 0a0710
button             = 1a1320
button-secondary   = 7dff7a
button-active      = a8ff54
button-disabled    = 1a1320
nav-active         = 0f0a16
play-button        = a8ff54
tab-active         = 0a0710
notification       = 0a0710
notification-error = 0a0710
playback-bar       = a8ff54
misc               = 7a7a6a
