#!/bin/bash
# wallpaper picker - awww only, no theme changes

source "$HOME/.config/hypr/scripts/wallpaper-lib.sh"

wallpaper_dir="$HOME/Wallpapers"
awww_params="--transition-fps 120 --transition-type center --transition-pos bottom --transition-duration 1 --transition-bezier 0.25,0.1,0.25,1.0"

mapfile -d '' wallpapers < <(find "$wallpaper_dir" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" \) -print0)

if [[ ${#wallpapers[@]} -eq 0 ]]; then
	(action=$(notify-send -A "open=Get Wallpapers" --wait "No Wallpapers Found" "Add images to ~/Wallpapers to use dynamic theming") && [[ "$action" == "open" ]] && xdg-open "https://github.com/Jmartgraphix/Wallpapers") &
	exit 1
fi

menu() {
	for wp in "${wallpapers[@]}"; do
		printf "%s\x00icon\x1f%s\n" "$(basename "$wp")" "$wp"
	done | sort
}

ensure_awww_daemon

choice=$(menu | rofi -i -dmenu -p "" -config ~/.config/rofi/custom-rofi/config-wallpaper.rasi)
[[ -z "$choice" ]] && exit 0

for wp in "${wallpapers[@]}"; do
	[[ "$(basename "$wp")" == "$choice" ]] || continue

	awww img "$wp" $awww_params
	sync_hyprlock_wallpaper "$wp"

	notify-send -i "$wp" "Wallpaper" "${wp##*/}"
	break
done
